# Site
name: "Puneet Singh Ludu"
description: "Machine Learning Engineer"
meta_description: "My Website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: ''
disqus: 'puneetsl'

# Authors
authors:
  Puneet:
    name: Puneet
    display_name: Puneet
    email: puneet.ludu@gmail.com
    web: http://www.puneetsingh.me
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
