# Site
name: "Puneet Singh Ludu"
title: "Puneet Singh Ludu"
description: "Machine Learning Architecture & Innovation"
meta_description: "My Website"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'G-NQW8G553M1'
disqus: 'puneetsl'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  puneet:
    name: Puneet Singh Ludu
    display_name: Puneet
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: puneet.ludu@gmail.com
    web: https://www.puneet.io
    twitter: https://twitter.com/puneetsl
    description: "Machine Learning Engineer at Zillow. Focused on ML Architecture & Innovation."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-katex
  - jekyll-mermaid

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /blog/page:num/

# Other
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images
lazyimages: "enabled"

# Sass
sass:
  style: compressed
  quiet_deps: true  # Suppress deprecation warnings from dependencies

# Mermaid
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js'
  initialize: >
    {
      "theme": "default",
      "themeVariables": {
        "darkMode": false
      },
      "securityLevel": "loose",
      "startOnLoad": true
    }

# Math rendering (KaTeX)
katex:
  rendering_options:
    throw_error: true
    output: mathml

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
